// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: agg_cal_task_service.proto

package agg_task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        string                 `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Proof         string                 `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggRequest) Reset() {
	*x = AggRequest{}
	mi := &file_agg_cal_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggRequest) ProtoMessage() {}

func (x *AggRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agg_cal_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggRequest.ProtoReflect.Descriptor instead.
func (*AggRequest) Descriptor() ([]byte, []int) {
	return file_agg_cal_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *AggRequest) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *AggRequest) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

type AggResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggResponse) Reset() {
	*x = AggResponse{}
	mi := &file_agg_cal_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggResponse) ProtoMessage() {}

func (x *AggResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agg_cal_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggResponse.ProtoReflect.Descriptor instead.
func (*AggResponse) Descriptor() ([]byte, []int) {
	return file_agg_cal_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *AggResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_agg_cal_task_service_proto protoreflect.FileDescriptor

const file_agg_cal_task_service_proto_rawDesc = "" +
	"\n" +
	"\x1aagg_cal_task_service.proto\x12\x05proto\":\n" +
	"\n" +
	"AggRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\tR\x06height\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\tR\x05proof\"#\n" +
	"\vAggResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2U\n" +
	"\x13AggCalculateService\x12>\n" +
	"\x13AddAggCalculateTask\x12\x11.proto.AggRequest\x1a\x12.proto.AggResponse\"\x00B\vZ\t/agg_taskb\x06proto3"

var (
	file_agg_cal_task_service_proto_rawDescOnce sync.Once
	file_agg_cal_task_service_proto_rawDescData []byte
)

func file_agg_cal_task_service_proto_rawDescGZIP() []byte {
	file_agg_cal_task_service_proto_rawDescOnce.Do(func() {
		file_agg_cal_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agg_cal_task_service_proto_rawDesc), len(file_agg_cal_task_service_proto_rawDesc)))
	})
	return file_agg_cal_task_service_proto_rawDescData
}

var file_agg_cal_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agg_cal_task_service_proto_goTypes = []any{
	(*AggRequest)(nil),  // 0: proto.AggRequest
	(*AggResponse)(nil), // 1: proto.AggResponse
}
var file_agg_cal_task_service_proto_depIdxs = []int32{
	0, // 0: proto.AggCalculateService.AddAggCalculateTask:input_type -> proto.AggRequest
	1, // 1: proto.AggCalculateService.AddAggCalculateTask:output_type -> proto.AggResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agg_cal_task_service_proto_init() }
func file_agg_cal_task_service_proto_init() {
	if File_agg_cal_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agg_cal_task_service_proto_rawDesc), len(file_agg_cal_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agg_cal_task_service_proto_goTypes,
		DependencyIndexes: file_agg_cal_task_service_proto_depIdxs,
		MessageInfos:      file_agg_cal_task_service_proto_msgTypes,
	}.Build()
	File_agg_cal_task_service_proto = out.File
	file_agg_cal_task_service_proto_goTypes = nil
	file_agg_cal_task_service_proto_depIdxs = nil
}
