// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: agg_cal_task_service.proto

package agg_task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggCalculateService_AddAggCalculateTask_FullMethodName = "/proto.AggCalculateService/AddAggCalculateTask"
)

// AggCalculateServiceClient is the client API for AggCalculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggCalculateServiceClient interface {
	AddAggCalculateTask(ctx context.Context, in *AggRequest, opts ...grpc.CallOption) (*AggResponse, error)
}

type aggCalculateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggCalculateServiceClient(cc grpc.ClientConnInterface) AggCalculateServiceClient {
	return &aggCalculateServiceClient{cc}
}

func (c *aggCalculateServiceClient) AddAggCalculateTask(ctx context.Context, in *AggRequest, opts ...grpc.CallOption) (*AggResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggResponse)
	err := c.cc.Invoke(ctx, AggCalculateService_AddAggCalculateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggCalculateServiceServer is the server API for AggCalculateService service.
// All implementations must embed UnimplementedAggCalculateServiceServer
// for forward compatibility.
type AggCalculateServiceServer interface {
	AddAggCalculateTask(context.Context, *AggRequest) (*AggResponse, error)
	mustEmbedUnimplementedAggCalculateServiceServer()
}

// UnimplementedAggCalculateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggCalculateServiceServer struct{}

func (UnimplementedAggCalculateServiceServer) AddAggCalculateTask(context.Context, *AggRequest) (*AggResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAggCalculateTask not implemented")
}
func (UnimplementedAggCalculateServiceServer) mustEmbedUnimplementedAggCalculateServiceServer() {}
func (UnimplementedAggCalculateServiceServer) testEmbeddedByValue()                             {}

// UnsafeAggCalculateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggCalculateServiceServer will
// result in compilation errors.
type UnsafeAggCalculateServiceServer interface {
	mustEmbedUnimplementedAggCalculateServiceServer()
}

func RegisterAggCalculateServiceServer(s grpc.ServiceRegistrar, srv AggCalculateServiceServer) {
	// If the following call pancis, it indicates UnimplementedAggCalculateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggCalculateService_ServiceDesc, srv)
}

func _AggCalculateService_AddAggCalculateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggCalculateServiceServer).AddAggCalculateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggCalculateService_AddAggCalculateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggCalculateServiceServer).AddAggCalculateTask(ctx, req.(*AggRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggCalculateService_ServiceDesc is the grpc.ServiceDesc for AggCalculateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggCalculateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AggCalculateService",
	HandlerType: (*AggCalculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAggCalculateTask",
			Handler:    _AggCalculateService_AddAggCalculateTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agg_cal_task_service.proto",
}
