package main

import (
	"flag"
	"github.com/txhsl/neox-dbft-verifier/config"
	"github.com/txhsl/neox-dbft-verifier/workflow/manager"
	"github.com/txhsl/neox-dbft-verifier/workflow/n3"
	"github.com/txhsl/neox-dbft-verifier/workflow/neox"
)

// main runs the VerifierNode impl, the common_config.json is generated by script in cmd/workflow
// then we can build a binary for this repo, and go run
// the common_config.json will be moved into the same dir using scripts
func main() {
	var (
		job        string
		configPath string
		chain      string
	)
	flag.StringVar(&chain, "chain", "neox", "chain type, n3 or neox")
	flag.StringVar(&job, "job", "node", "node job, manager or node")
	flag.StringVar(&configPath, "config", "common_config.json", "config json file for loading config into node or manager")
	flag.Parse()
	if chain != "neox" && chain != "n3" {
		panic("invalid chain")
	}
	if job != "node" && job != "manager" {
		panic("invalid job")
	}
	switch job {
	case "node":
		commonConfig, err := config.LoadConfigFromJson(configPath)
		if err != nil {
			panic(err)
		}
		switch commonConfig.Job {
		case config.Worker:
			if chain == "neox" {
				var worker neox.Worker
				err = worker.FromCommonConfig(commonConfig)
				if err != nil {
					panic(err)
				}
				err = worker.Start() // blocked
				if err != nil {
					panic(err)
				}
			} else {
				var worker n3.Worker
				err = worker.FromCommonConfig(commonConfig)
				if err != nil {
					panic(err)
				}
				err = worker.Start()
				if err != nil {
					panic(err)
				}
			}
		case config.Aggregator:
			var aggregator neox.Aggregator
			err = aggregator.FromCommonConfig(commonConfig)
			if err != nil {
				panic(err)
			}
			err = aggregator.Start() // blocked
			if err != nil {
				panic(err)
			}

		default:
			panic("invalid node job")

		}
	case "manager":
		m := new(manager.BlockManager)

		err := m.FromJson("../cmd/workflow/configs/manager.json")
		if err != nil {
			panic(err)
		}
		err = m.Start()
		if err != nil {
			panic(err)
		}
		for err := range m.Feedback() {
			panic(err)
		}
	default:
		panic("invalid job")
	}
}
