package main

import (
	"flag"
	"github.com/txhsl/neox-dbft-verifier/config"
	"github.com/txhsl/neox-dbft-verifier/workflow"
)

// main runs the VerifierNode impl, the common_config.json is generated by script in cmd/workflow
// then we can build a binary for this repo, and go run
// the common_config.json will be moved into the same dir using scripts
func main() {
	var (
		job        string
		configPath string
	)
	flag.StringVar(&job, "job", "node", "node job, manager or node")
	flag.StringVar(&configPath, "config", "common_config.json", "config json file for loading config into node or manager")
	flag.Parse()
	switch job {
	case "node":
		commonConfig, err := config.LoadConfigFromJson(configPath)
		if err != nil {
			panic(err)
		}
		switch commonConfig.Job {
		case config.Worker:
			var worker workflow.Worker
			err = worker.FromCommonConfig(commonConfig)
			if err != nil {
				panic(err)
			}
			err = worker.Start() // blocked
			if err != nil {
				panic(err)
			}
		case config.Aggregator:
			var aggregator workflow.Aggregator
			err = aggregator.FromCommonConfig(commonConfig)
			if err != nil {
				panic(err)
			}
			err = aggregator.Start() // blocked
			if err != nil {
				panic(err)
			}

		default:
			panic("invalid node job")

		}
	case "manager":
		manager := new(workflow.BlockManager)
		err := manager.FromJson("../cmd/workflow/configs/manager.json")
		if err != nil {
			panic(err)
		}
		err = manager.Start()
		if err != nil {
			panic(err)
		}
		for err := range manager.Feedback() {
			panic(err)
		}
	default:
		panic("invalid job")
	}
}
