// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: sub_cal_task_service.proto

package sub_task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubCalculateService_AddSubCalculateTask_FullMethodName = "/proto.SubCalculateService/AddSubCalculateTask"
)

// SubCalculateServiceClient is the client API for SubCalculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubCalculateServiceClient interface {
	AddSubCalculateTask(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (*SubResponse, error)
}

type subCalculateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubCalculateServiceClient(cc grpc.ClientConnInterface) SubCalculateServiceClient {
	return &subCalculateServiceClient{cc}
}

func (c *subCalculateServiceClient) AddSubCalculateTask(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (*SubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubResponse)
	err := c.cc.Invoke(ctx, SubCalculateService_AddSubCalculateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubCalculateServiceServer is the server API for SubCalculateService service.
// All implementations must embed UnimplementedSubCalculateServiceServer
// for forward compatibility.
type SubCalculateServiceServer interface {
	AddSubCalculateTask(context.Context, *SubRequest) (*SubResponse, error)
	mustEmbedUnimplementedSubCalculateServiceServer()
}

// UnimplementedSubCalculateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubCalculateServiceServer struct{}

func (UnimplementedSubCalculateServiceServer) AddSubCalculateTask(context.Context, *SubRequest) (*SubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSubCalculateTask not implemented")
}
func (UnimplementedSubCalculateServiceServer) mustEmbedUnimplementedSubCalculateServiceServer() {}
func (UnimplementedSubCalculateServiceServer) testEmbeddedByValue()                             {}

// UnsafeSubCalculateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubCalculateServiceServer will
// result in compilation errors.
type UnsafeSubCalculateServiceServer interface {
	mustEmbedUnimplementedSubCalculateServiceServer()
}

func RegisterSubCalculateServiceServer(s grpc.ServiceRegistrar, srv SubCalculateServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubCalculateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubCalculateService_ServiceDesc, srv)
}

func _SubCalculateService_AddSubCalculateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCalculateServiceServer).AddSubCalculateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCalculateService_AddSubCalculateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCalculateServiceServer).AddSubCalculateTask(ctx, req.(*SubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubCalculateService_ServiceDesc is the grpc.ServiceDesc for SubCalculateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubCalculateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SubCalculateService",
	HandlerType: (*SubCalculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSubCalculateTask",
			Handler:    _SubCalculateService_AddSubCalculateTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sub_cal_task_service.proto",
}
