// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: sub_cal_task_service.proto

package sub_task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headdata      string                 `protobuf:"bytes,1,opt,name=headdata,proto3" json:"headdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	mi := &file_sub_cal_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sub_cal_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_sub_cal_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubRequest) GetHeaddata() string {
	if x != nil {
		return x.Headdata
	}
	return ""
}

type SubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubResponse) Reset() {
	*x = SubResponse{}
	mi := &file_sub_cal_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse) ProtoMessage() {}

func (x *SubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sub_cal_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse.ProtoReflect.Descriptor instead.
func (*SubResponse) Descriptor() ([]byte, []int) {
	return file_sub_cal_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_sub_cal_task_service_proto protoreflect.FileDescriptor

const file_sub_cal_task_service_proto_rawDesc = "" +
	"\n" +
	"\x1asub_cal_task_service.proto\x12\x05proto\"(\n" +
	"\n" +
	"SubRequest\x12\x1a\n" +
	"\bheaddata\x18\x01 \x01(\tR\bheaddata\"#\n" +
	"\vSubResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2U\n" +
	"\x13SubCalculateService\x12>\n" +
	"\x13AddSubCalculateTask\x12\x11.proto.SubRequest\x1a\x12.proto.SubResponse\"\x00B\vZ\t/sub_taskb\x06proto3"

var (
	file_sub_cal_task_service_proto_rawDescOnce sync.Once
	file_sub_cal_task_service_proto_rawDescData []byte
)

func file_sub_cal_task_service_proto_rawDescGZIP() []byte {
	file_sub_cal_task_service_proto_rawDescOnce.Do(func() {
		file_sub_cal_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub_cal_task_service_proto_rawDesc), len(file_sub_cal_task_service_proto_rawDesc)))
	})
	return file_sub_cal_task_service_proto_rawDescData
}

var file_sub_cal_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sub_cal_task_service_proto_goTypes = []any{
	(*SubRequest)(nil),  // 0: proto.SubRequest
	(*SubResponse)(nil), // 1: proto.SubResponse
}
var file_sub_cal_task_service_proto_depIdxs = []int32{
	0, // 0: proto.SubCalculateService.AddSubCalculateTask:input_type -> proto.SubRequest
	1, // 1: proto.SubCalculateService.AddSubCalculateTask:output_type -> proto.SubResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sub_cal_task_service_proto_init() }
func file_sub_cal_task_service_proto_init() {
	if File_sub_cal_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub_cal_task_service_proto_rawDesc), len(file_sub_cal_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sub_cal_task_service_proto_goTypes,
		DependencyIndexes: file_sub_cal_task_service_proto_depIdxs,
		MessageInfos:      file_sub_cal_task_service_proto_msgTypes,
	}.Build()
	File_sub_cal_task_service_proto = out.File
	file_sub_cal_task_service_proto_goTypes = nil
	file_sub_cal_task_service_proto_depIdxs = nil
}
