// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: aggregate.proto

package aggregate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregateService_Commit_FullMethodName = "/proto.AggregateService/Commit"
)

// AggregateServiceClient is the client API for AggregateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregateServiceClient interface {
	Commit(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
}

type aggregateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateServiceClient(cc grpc.ClientConnInterface) AggregateServiceClient {
	return &aggregateServiceClient{cc}
}

func (c *aggregateServiceClient) Commit(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, AggregateService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateServiceServer is the server API for AggregateService service.
// All implementations must embed UnimplementedAggregateServiceServer
// for forward compatibility.
type AggregateServiceServer interface {
	Commit(context.Context, *AggregateRequest) (*AggregateResponse, error)
	mustEmbedUnimplementedAggregateServiceServer()
}

// UnimplementedAggregateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregateServiceServer struct{}

func (UnimplementedAggregateServiceServer) Commit(context.Context, *AggregateRequest) (*AggregateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedAggregateServiceServer) mustEmbedUnimplementedAggregateServiceServer() {}
func (UnimplementedAggregateServiceServer) testEmbeddedByValue()                          {}

// UnsafeAggregateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateServiceServer will
// result in compilation errors.
type UnsafeAggregateServiceServer interface {
	mustEmbedUnimplementedAggregateServiceServer()
}

func RegisterAggregateServiceServer(s grpc.ServiceRegistrar, srv AggregateServiceServer) {
	// If the following call pancis, it indicates UnimplementedAggregateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregateService_ServiceDesc, srv)
}

func _AggregateService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServiceServer).Commit(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregateService_ServiceDesc is the grpc.ServiceDesc for AggregateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AggregateService",
	HandlerType: (*AggregateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commit",
			Handler:    _AggregateService_Commit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aggregate.proto",
}
