// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: aggregate.proto

package aggregate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int32 height = 1; // blockHeight is no need, in blockHeader
	BlockHash     []byte `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"` // blockHash, for map[blockHash]types.Header to get a header and compute the public inputs
	Proof         []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`         // proof, no public witness
	Circuit       int32  `protobuf:"varint,3,opt,name=circuit,proto3" json:"circuit,omitempty"`    // which circuit is the proof proves
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_aggregate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_aggregate_proto_rawDescGZIP(), []int{0}
}

func (x *AggregateRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *AggregateRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *AggregateRequest) GetCircuit() int32 {
	if x != nil {
		return x.Circuit
	}
	return 0
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_aggregate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_aggregate_proto_rawDescGZIP(), []int{1}
}

func (x *AggregateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_aggregate_proto protoreflect.FileDescriptor

const file_aggregate_proto_rawDesc = "" +
	"\n" +
	"\x0faggregate.proto\x12\x05proto\"`\n" +
	"\x10AggregateRequest\x12\x1c\n" +
	"\tblockHash\x18\x01 \x01(\fR\tblockHash\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12\x18\n" +
	"\acircuit\x18\x03 \x01(\x05R\acircuit\"-\n" +
	"\x11AggregateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Q\n" +
	"\x10AggregateService\x12=\n" +
	"\x06Commit\x12\x17.proto.AggregateRequest\x1a\x18.proto.AggregateResponse\"\x00B\fZ\n" +
	"/aggregateb\x06proto3"

var (
	file_aggregate_proto_rawDescOnce sync.Once
	file_aggregate_proto_rawDescData []byte
)

func file_aggregate_proto_rawDescGZIP() []byte {
	file_aggregate_proto_rawDescOnce.Do(func() {
		file_aggregate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregate_proto_rawDesc), len(file_aggregate_proto_rawDesc)))
	})
	return file_aggregate_proto_rawDescData
}

var file_aggregate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aggregate_proto_goTypes = []any{
	(*AggregateRequest)(nil),  // 0: proto.AggregateRequest
	(*AggregateResponse)(nil), // 1: proto.AggregateResponse
}
var file_aggregate_proto_depIdxs = []int32{
	0, // 0: proto.AggregateService.Commit:input_type -> proto.AggregateRequest
	1, // 1: proto.AggregateService.Commit:output_type -> proto.AggregateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aggregate_proto_init() }
func file_aggregate_proto_init() {
	if File_aggregate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregate_proto_rawDesc), len(file_aggregate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregate_proto_goTypes,
		DependencyIndexes: file_aggregate_proto_depIdxs,
		MessageInfos:      file_aggregate_proto_msgTypes,
	}.Build()
	File_aggregate_proto = out.File
	file_aggregate_proto_goTypes = nil
	file_aggregate_proto_depIdxs = nil
}
