// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: distribute.proto

package distribute

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistributeService_SendBlock_FullMethodName = "/proto.DistributeService/SendBlock"
)

// DistributeServiceClient is the client API for DistributeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistributeServiceClient interface {
	SendBlock(ctx context.Context, in *BlockDistributeRequest, opts ...grpc.CallOption) (*BlockDistributeResponse, error)
}

type distributeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributeServiceClient(cc grpc.ClientConnInterface) DistributeServiceClient {
	return &distributeServiceClient{cc}
}

func (c *distributeServiceClient) SendBlock(ctx context.Context, in *BlockDistributeRequest, opts ...grpc.CallOption) (*BlockDistributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockDistributeResponse)
	err := c.cc.Invoke(ctx, DistributeService_SendBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributeServiceServer is the server API for DistributeService service.
// All implementations must embed UnimplementedDistributeServiceServer
// for forward compatibility.
type DistributeServiceServer interface {
	SendBlock(context.Context, *BlockDistributeRequest) (*BlockDistributeResponse, error)
	mustEmbedUnimplementedDistributeServiceServer()
}

// UnimplementedDistributeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistributeServiceServer struct{}

func (UnimplementedDistributeServiceServer) SendBlock(context.Context, *BlockDistributeRequest) (*BlockDistributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBlock not implemented")
}
func (UnimplementedDistributeServiceServer) mustEmbedUnimplementedDistributeServiceServer() {}
func (UnimplementedDistributeServiceServer) testEmbeddedByValue()                           {}

// UnsafeDistributeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributeServiceServer will
// result in compilation errors.
type UnsafeDistributeServiceServer interface {
	mustEmbedUnimplementedDistributeServiceServer()
}

func RegisterDistributeServiceServer(s grpc.ServiceRegistrar, srv DistributeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDistributeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistributeService_ServiceDesc, srv)
}

func _DistributeService_SendBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockDistributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributeServiceServer).SendBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributeService_SendBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributeServiceServer).SendBlock(ctx, req.(*BlockDistributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistributeService_ServiceDesc is the grpc.ServiceDesc for DistributeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DistributeService",
	HandlerType: (*DistributeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBlock",
			Handler:    _DistributeService_SendBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "distribute.proto",
}
