// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: distribute.proto

package distribute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockDistributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        []byte                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDistributeRequest) Reset() {
	*x = BlockDistributeRequest{}
	mi := &file_distribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDistributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDistributeRequest) ProtoMessage() {}

func (x *BlockDistributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDistributeRequest.ProtoReflect.Descriptor instead.
func (*BlockDistributeRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{0}
}

func (x *BlockDistributeRequest) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

type BlockDistributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDistributeResponse) Reset() {
	*x = BlockDistributeResponse{}
	mi := &file_distribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDistributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDistributeResponse) ProtoMessage() {}

func (x *BlockDistributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDistributeResponse.ProtoReflect.Descriptor instead.
func (*BlockDistributeResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{1}
}

func (x *BlockDistributeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_distribute_proto protoreflect.FileDescriptor

const file_distribute_proto_rawDesc = "" +
	"\n" +
	"\x10distribute.proto\x12\x05proto\"0\n" +
	"\x16BlockDistributeRequest\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\"3\n" +
	"\x17BlockDistributeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2a\n" +
	"\x11DistributeService\x12L\n" +
	"\tSendBlock\x12\x1d.proto.BlockDistributeRequest\x1a\x1e.proto.BlockDistributeResponse\"\x00B\rZ\v/distributeb\x06proto3"

var (
	file_distribute_proto_rawDescOnce sync.Once
	file_distribute_proto_rawDescData []byte
)

func file_distribute_proto_rawDescGZIP() []byte {
	file_distribute_proto_rawDescOnce.Do(func() {
		file_distribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distribute_proto_rawDesc), len(file_distribute_proto_rawDesc)))
	})
	return file_distribute_proto_rawDescData
}

var file_distribute_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_distribute_proto_goTypes = []any{
	(*BlockDistributeRequest)(nil),  // 0: proto.BlockDistributeRequest
	(*BlockDistributeResponse)(nil), // 1: proto.BlockDistributeResponse
}
var file_distribute_proto_depIdxs = []int32{
	0, // 0: proto.DistributeService.SendBlock:input_type -> proto.BlockDistributeRequest
	1, // 1: proto.DistributeService.SendBlock:output_type -> proto.BlockDistributeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_distribute_proto_init() }
func file_distribute_proto_init() {
	if File_distribute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distribute_proto_rawDesc), len(file_distribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distribute_proto_goTypes,
		DependencyIndexes: file_distribute_proto_depIdxs,
		MessageInfos:      file_distribute_proto_msgTypes,
	}.Build()
	File_distribute_proto = out.File
	file_distribute_proto_goTypes = nil
	file_distribute_proto_depIdxs = nil
}
